plugins: 
   - {name: obstacles,        type: "costmap_2d::VoxelLayer"}    
   - {name: inflation_map,    type: "costmap_2d::InflationLayer"}
footprint: [[0.3, 0.2], [0.3, -0.2], [-0.3, -0.2], [-0.3, 0.2]]
inflation_map:
   inflation_radius : 3
   cost_scaling_factor : 10
width: 6
height: 6
update_frequency: 30
publish_frequency: 20
rolling_window: true
robot_base_frame: base_link
global_frame: odom
resolution: 0.05
obstacles:
   obstacle_range: 4
   raytrace_range: 0.5
   observation_sources : base_scan
   base_scan : 
      data_type: LaserScan
      topic: laser_scan
      sensor_frame: base_laser_link
      clearing: true
      marking: true
      observation_persistence: 0.5
      expected_update_rate: 0.0
      inf_is_valid: true